replace spaces in urls
revirtux/BetaSeferSite pull request #36
Opened 2021-01-24 07:00 UTC by revirtux

now there are no spaces in the URLs of houses and categories  #35

2021-01-24 07:03 UTC, revirtux commented on index/views.py
> +        name=category_name.replace("-", " "))
oppsy

2021-01-24 07:03 UTC, revirtux commented on index/views.py
> +        name=category_name.replace("-", " "))
fixed!

2021-01-24 11:45 UTC, AmitTPB requested changes

2021-01-24 11:45 UTC, AmitTPB commented on index/views.py
> +    house_name = house_name.replace("-", " ")
This ruins the css files somehow, fix it
![image](https://user-images.githubusercontent.com/62648009/105629215-5fa26080-5e4a-11eb-93e4-0ec9b63c7648.png)

2021-01-24 19:22 UTC, revirtux commented on index/views.py
> +    house_name = house_name.replace("-", " ")
הוספתי תיקון גם לCSS

2021-01-25 11:02 UTC, AmitTPB requested changes

2021-01-25 11:02 UTC, AmitTPB commented on index/views.py
> +    house_name = house_name.replace("-", " ")
![image](https://user-images.githubusercontent.com/62648009/105697660-7fe72380-5f0d-11eb-92fa-62198358160a.png)
now the images won't work

2021-01-27 19:56 UTC, AmitTPB commented on index/views.py
> +    house_name = house_name.replace("-", " ")
nvm

2021-01-27 19:59 UTC, AmitTPB approved these changes
Yes it works you can do the thingy now

2021-01-27 19:59 UTC, merged